Adding Mega NZ custom
meganz/perfect-scrollbar pull request #2
Opened 2023-12-21 05:19 UTC by sabdol

Thank you very much for your contribution! Please make sure the followings
are checked.

- [ ] Read [CONTRIBUTING.md](../CONTRIBUTING.md)
- [ ] Run `npm test` to make sure it formats and build successfully
- [ ] Provide the scenario this PR will address(some JSFiddles will be perfect)
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Refer to concerning issues if exist

2023-12-21 12:42 UTC, diegocr requested changes
i think will be good if we do adhere to the Rollup build process instead of directly modifying the "dist" file.

2023-12-22 00:52 UTC, sabdol commented
> i think will be good if we do adhere to the Rollup build process instead of directly modifying the "dist" file.

Done as you asked and update code here and their to avoid their test complains

2023-12-27 17:35 UTC, diegocr approved these changes

2023-12-27 17:35 UTC, diegocr commented on package.json
> +  "version": "1.5.5-MEGA",
```suggestion
  "version": "1.5.5",
```

2023-12-27 17:42 UTC, merged

2023-12-27 19:48 UTC, diegocr commented on src/index.js
> +    if (element.classList.contains('ps-disabled')) {
Have you actually tested this? i may merged this too prematurely, since i think here you meant to use `this.element` (and in other similar places?)

2023-12-27 20:04 UTC, diegocr commented on src/index.js
> +    if (element.classList.contains('ps-disabled')) {
The other were fine, sorted this one with [bd2e703](https://github.com/meganz/perfect-scrollbar/commit/bd2e7037e8961575e0f4f1f255938355022e37dd)